apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sites-applicationset
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - name: site-a
            path: sites/site-a
          - name: site-b
            path: sites/site-b
  template:
    # Template for Hub Clusters
    metadata:
      name: '{{.name}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        targetRevision: kriel
        path: application-sets/
      helm:
        parameters:
          - name: site
            value: '{{.name}}' # Pass the site context
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true