apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-infrastructure
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        revision: kriel
        files:
          # Dynamically match hub-clusters YAMLs for the specific site
          - path: sites/{{ .Values.parameters.site }}/hub-clusters/*.yaml
  template:
    metadata:
      name: '{{ .Values.parameters.site }}-{{ .Values.parameters.pathBasename }}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        path: hub-infrastructure-chart # Path to the Helm chart for hub clusters
        targetRevision: kriel
        helm:
          valueFiles:
            - global-values/values.yaml                # Global values
            - sites/{{ .Values.parameters.site }}/site.yaml      # Site-specific values
            - '{{ .Values.parameters.path }}'                               # Cluster-specific values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .Values.parameters.site }}-hub-cluster'  # Namespace based on the site
      syncPolicy:
        automated:
          prune: true
          selfHeal: true