apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{ .Values.site }}-tenant-clusters'
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        revision: kriel
        files:
          - path: sites/{{ .Values.site }}/clusters/*.yaml # Restrict to the passed site
    - parameters:
        - name: site # Use the passed site from parent
  template:
    metadata:
      name: '{{"{{"}}path.filename{{"}}"}}-tenant-cluster'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        path: tenant-chart
        targetRevision: kriel
        helm:
          valueFiles:
            - global-values/values.yaml
            - '{{"{{"}}path{{"}}"}}/../../site.yaml'
            - '{{"{{"}}path{{"}}"}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true