apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-clusters
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        revision: kriel
        files:
          - path: sites/{{ .Values.parameters.site }}/clusters/*.yaml # Restrict to the passed site
    - parameters:
        - name: site # Use the passed site from parent
  template:
    metadata:
      name: '{{ .Values.path-filename }}-tenant-cluster'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        path: tenant-chart
        targetRevision: kriel
        helm:
          valueFiles:
            - global-values/values.yaml
            - '{{ .Values.path-dir }}/../../site.yaml'
            - '{{ .Values.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'clusters-{{ .Values.path-filename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true