apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/your-org/gitops-repo.git'
        revision: main
        files:
          # Dynamically match hub-clusters YAMLs for the specific site
          - path: sites/{{parameters.site}}/hub-clusters/*.yaml
  template:
    metadata:
      name: '{{parameters.site}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-org/gitops-repo.git'
        path: hub-infrastructure-chart # Path to the Helm chart for hub clusters
        targetRevision: main
        helm:
          valueFiles:
            - global-values/values.yaml                # Global values
            - sites/{{parameters.site}}/site.yaml      # Site-specific values
            - '{{path}}'                               # Cluster-specific values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{parameters.site}}-hub-cluster'  # Namespace based on the site
      syncPolicy:
        automated:
          prune: true
          selfHeal: true