apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sites-applicationset
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - name: site-a
            path: sites/site-a
          - name: site-b
            path: sites/site-b
  templates:
    # Template for Hub Clusters
    - metadata:
        name: '{{.name}}-hub-clusters'
      spec:
        project: default
        source:
          repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
          targetRevision: main
          path: application-sets/hub-infrastructure.yaml
        helm:
          parameters:
            - name: site
              value: '{{.name}}' # Pass the site context
        destination:
          server: https://kubernetes.default.svc
          namespace: openshift-gitops
        syncPolicy:
          automated:
            prune: true
            selfHeal: true

    # Template for Tenant Clusters
    - metadata:
        name: '{{.name}}-tenant-clusters'
      spec:
        project: default
        source:
          repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
          targetRevision: main
          path: application-sets/tenant-clusters.yaml
        helm:
          parameters:
            - name: site
              value: '{{.name}}' # Pass the site context
        destination:
          server: https://kubernetes.default.svc
          namespace: openshift-gitops
        syncPolicy:
          automated:
            prune: true
            selfHeal: true