apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-clusters
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        revision: main
        files:
          - path: sites/{{parameters.site}}/clusters/*.yaml # Restrict to the passed site
    - parameters:
        - name: site # Use the passed site from parent
  template:
    metadata:
      name: '{{path.filename}}-tenant-cluster'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/matankriel/hcp-gitops-demo.git'
        path: tenant-chart
        targetRevision: main
        helm:
          valueFiles:
            - global-values/values.yaml
            - '{{path.dir}}/../../site.yaml'
            - '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.filename}}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true